production:
  url:
  name: Spring Base API
  database:
    driver: com.mysql.jdbc.Driver
    url:
    username:
    password:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: false
    hbm2ddl.auto: update
    jdbc_batch_size: 20
    entity_manager:
      packages_to_scan:
        - com.roms.module.user.domain.model
        - com.roms.module.translation.domain.model
  i18n:
    message_source:
      cache_time: 600
    locale:
      default: en
      resolver:
        cookie_time: 31536000 # 1 year
  resource:
    cache_time: 31536000 # 1 year
  mail:
    smtp:
      host:
      username:
      password:
      port: 25
    default_sender: noreply@springbaseroms.ch
staging:
  url:
  name: \[STAGING\] Spring Base API
  mail:
    redirect_to: staging@springbaseroms.ch
dev:
  name: \[DEVELOP\] Spring Base API
  hibernate:
    show_sql: true
  i18n:
    message_source:
      cache_time: -1
  resource:
    cache_time: 0
  mail:
    redirect_to:
test:
  name: \[TEST\] Spring Base API
  mail:
    dry_mode: true

