production:
  url:
  name: Spring Base API
  database:
    driver: com.mysql.jdbc.Driver
    url:
    username:
    password:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: false
    hbm2ddl.auto: update
    entity_manager:
      packages_to_scan:
        - com.roms.module.user.domain.model
        - com.roms.module.translation.domain.model
  i18n:
    message_source:
      cache_time: 600
      use_code_as_default_message: true
    locale:
      default: en
      resolver:
        cookie_time: 31536000 # 1 year
  resource:
    cache_time: 31536000 # 1 year
staging:
  url:
  name: \[STAGING\] Spring Base API
dev:
  name: \[DEVELOP\] Spring Base API
  hibernate:
    show_sql: true
  i18n:
    message_source:
      cache_time: -1
  resource:
    cache_time: 0
test:
  database:
    url: jdbc:mysql://localhost:3306/springtest
    username: springtest
    password: springtest